-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') "SALES_DATE", PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where to_char(SALES_DATE, 'YYYY-MM') = '2022-03'
union all
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') "SALES_DATE", PRODUCT_ID, null, SALES_AMOUNT
from OFFLINE_SALE
where to_char(SALES_DATE, 'YYYY-MM') = '2022-03'
order by SALES_DATE, PRODUCT_ID, user_id