-- 코드를 입력하세요
SELECT p.PRODUCT_ID, PRODUCT_NAME, sum(PRICE * amount) as "TOTAL_SALES"
from FOOD_PRODUCT p
join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where month(PRODUCE_DATE) = 5
group by p.PRODUCT_ID, PRODUCT_NAME
order by TOTAL_SALES desc, p.PRODUCT_ID