-- 코드를 작성해주세요
select HR_DEPARTMENT.DEPT_ID, DEPT_NAME_EN, Round(avg(SAL), 0) as "AVG_SAL"
from HR_DEPARTMENT, HR_EMPLOYEES
where HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
group by HR_DEPARTMENT.DEPT_ID
order by AVG_SAL desc